Repository skku-comit/comit-website, pull requests merged in 2024-09, with the labels that each got.

#156 feat(fe): change sidebar to use shadcn sheet
  components/admin/Sidebar/NavLink.tsx
  components/admin/Sidebar/index.tsx
  components/ui/sheet.tsx
  package-lock.json
  package.json
Labels: feature

#157 124 add auth at and rt
  .vscode/launch.json
  app/(main)/login/page.tsx
  app/(main)/signup/page.tsx
  app/(main)/study/[id]/signup/page.tsx
  app/(main)/study/open/page.tsx
  app/admin/page.tsx
  app/admin/studies/page.tsx
  components/about/MemberList.tsx
  components/admin/DataTable/EditableCell.tsx
  components/admin/DataTable/columns/Study.tsx
  components/main/ExampleStudyList.tsx
  components/study/StudyList.tsx
  components/study/signup/StudySignupForm.tsx
  constants/apiEndpoint.ts
  constants/zodSchema/signin.ts
  constants/zodSchema/signup.ts
  lib/auth/AuthProvider.tsx
  lib/auth/README.md
  lib/auth/auth.ts
  lib/auth/callbackFunctions/README.md
  lib/auth/callbackFunctions/parameters.ts
  lib/auth/utils.ts
  lib/fetch.ts
  middleware.ts
  package-lock.json
  package.json
  types/auth.d.ts
Labels: feature, API

#158 134 connect backend
  app/(main)/login/page.tsx
  app/(main)/study/[id]/signup/page.tsx
  app/(main)/study/open/page.tsx
  app/admin/page.tsx
  app/admin/studies/page.tsx
  app/admin/users/page.tsx
  app/api/studies/[id]/signup/route.ts
  components/about/IntroduceMemberCard.tsx
  components/about/MemberList.tsx
  components/admin/DataTable/EditableCell.tsx
  components/admin/DataTable/columns/Study.tsx
  components/admin/DataTable/columns/User.tsx
  components/common/StudyCard/index.tsx
  components/common/User/HoverCard.tsx
  components/main/ExampleStudyList.tsx
  components/study/StudyList.tsx
  components/study/signup/StudySignupForm.tsx
  constants/apiEndpoint.ts
  lib/auth/auth.ts
  lib/supabase/client.ts
  middleware.ts
  package-lock.json
  package.json
  types/auth.d.ts
  types/index.ts
Labels: fix, API

#168 chore: add redirection logic at signup page
  app/(main)/signup/page.tsx
Labels: chore

#169 feat(fe): add mystudy
  app/(main)/mystudy/[id]/page.tsx
  app/(main)/mystudy/feedback/page.tsx
  app/(main)/mystudy/layout.tsx
  app/(main)/mystudy/mystudy.css
  app/(main)/mystudy/page.tsx
  components/common/Header/Profile.tsx
  components/mystudy/MyStudyHeader.tsx
  components/mystudy/MyStudyNavBar.tsx
  components/ui/sheet.tsx
  components/ui/toast.tsx
  components/ui/tooltip.tsx
  components/ui/use-toast.ts
  constants/apiEndpoint.ts
  constants/routes.ts
  package-lock.json
  package.json
  tsconfig.json
  types/react-easy-edit.d.ts
  types/react-rating-stars-component.d.ts
Labels: feature

#174 fix(fe): fix about page fetch error
  components/about/IntroduceMemberCard.tsx
  components/about/MemberList.tsx
  components/admin/DataTable/ControlHeader.tsx
  components/admin/DataTable/RowAction.tsx
  components/admin/DataTable/columns/Study.tsx
  components/common/DataTable/ViewOptions.tsx
  types/index.ts
Labels: fix

#177 feat(fe): add patch position in user data table
  components/admin/DataTable/columns/User.tsx
  constants/apiEndpoint.ts
Labels: feature

#180 Fix minor UI bugs
  components/common/Header/Profile.tsx
  components/main/ExampleStudyList.tsx
  constants/routes.ts
  lib/auth/AuthProvider.tsx
  lib/auth/auth.ts
  lib/auth/callbackFunctions/parameters.ts
  types/auth.d.ts
Labels: fix, feature, API

#175 feat(fe): implement profile page
  app/(main)/mystudy/page.tsx
  app/(main)/profile/_components/ProfileCards.tsx
  app/(main)/profile/page.tsx
  components/admin/DataTable/ControlHeader.tsx
  constants/apiEndpoint.ts
  constants/zodSchema/profileUpdate.ts
  lib/supabase/hooks.ts
Labels: feature

#184 fix: show toast when signup failed
  app/(main)/profile/_components/ProfileCards.tsx
  app/(main)/signup/page.tsx
Labels: fix

#187 fix: delete pretendard, change korean text font bolder
  app/(main)/mystudy/layout.tsx
  app/(main)/mystudy/mystudy.css
  app/(main)/signup/page.tsx
  app/(main)/signup/signup.css
  components/common/Header/NavLink.tsx
  components/common/Header/Profile.tsx
  components/common/Header/index.tsx
Labels: chore

#193 fix: disable button right after fetch
  app/(main)/login/page.tsx
  app/(main)/signup/page.tsx
  app/(main)/study/open/page.tsx
  components/ui/tabs.tsx
  package-lock.json
  package.json
Labels: chore

#192 170 connect mypage with backend
  app/(main)/mystudy/[id]/page.tsx
  app/(main)/mystudy/page.tsx
  constants/apiEndpoint.ts
  lib/supabase/hooks.ts
Labels: chore, API

#196 chore: apply pretendard for whole project
  app/(main)/layout.tsx
  app/admin/layout.tsx
  app/layout.tsx
  public/fonts/PretendardVariable.woff2
  tailwind.config.ts
Labels: chore

#198 chore: set next CORS headers
  next.config.js
Labels: fix
