Repository skku-comit/comit-website, pull requests merged in 2024-03, with the labels that each got.

#38 feat(fe): add open study
  app/(main)/(light)/study/open/page.tsx
  components/ui/textarea.tsx
  package-lock.json
  package.json
Labels: feature

#37 chore: add favicon and metadata
  app/favicon.ico
  app/layout.tsx
  components/common/Footer.tsx
  components/common/Header.tsx
Labels: chore

#40 Chore/23 make dummy data
  app/(main)/(dark)/page.tsx
  lib/dummy.ts
Labels: chore

#42 feat/add animation to text
  app/(main)/(dark)/page.tsx
  package-lock.json
  package.json
Labels: feature

#44 feat/add animation to main page
  app/(main)/(dark)/page.tsx
  package-lock.json
  package.json
Labels: feature

#43 feat(fe) edit study card, change media query css
  app/(main)/(dark)/page.tsx
  app/(main)/(light)/about/page.tsx
  app/(main)/(light)/study/open/page.tsx
  app/(main)/(light)/study/page.tsx
  components/about/IntroduceMemberCard.tsx
  components/about/SectionCard.tsx
  components/clubroom/ClubroomInfoCard.tsx
  components/common/SectionBanner.tsx
  components/main/StudyCard.tsx
  components/study/StudyCard.tsx
  components/ui/alert-dialog.tsx
  components/ui/badge.tsx
  package-lock.json
  package.json
Labels: feature

#47 feat(fe): apply ksj comments
  app/(main)/(dark)/signup/page.tsx
  app/(main)/(light)/study/open/page.tsx
  app/(main)/(light)/study/page.tsx
  components/ui/popover.tsx
  package-lock.json
  package.json
Labels: fix

#50 feat/add animation to clubroom page and add carousel
  app/(main)/(light)/clubroom/page.tsx
Labels: feature

#49 fix: edit main page animation and carousel
  app/(main)/(dark)/page.tsx
  package-lock.json
  package.json
Labels: fix

#53 feat(fe): add admin study data table
  .eslintrc.json
  .husky/pre-commit
  app/admin/page.tsx
  components/columns/Study.tsx
  components/common/DataTable.tsx
  components/common/Header.tsx
  components/ui/table.tsx
  lib/dummy.ts
  package-lock.json
  package.json
Labels: feature

#62 feat(fe): edit clubroom carousel design
  app/(main)/(light)/clubroom/page.tsx
  components/clubroom/ClubroomCarousel.tsx
Labels: feature

#64 feat: add arrow to main page
  app/(main)/(dark)/page.tsx
Labels: feature

#65 style(fe): fix main page responsive style
  app/(main)/(dark)/page.tsx
Labels: style

#61 feat/add dropdown to header of admin page
  app/admin/closed/page.tsx
  app/admin/opened/page.tsx
  app/admin/reviewing/page.tsx
  app/admin/studies/page.tsx
  components/admin/Dropdown.tsx
  components/admin/SideBar.tsx
Labels: feature

#69 feat: add under construction dialog
  app/(main)/(dark)/login/page.tsx
  app/(main)/(dark)/signup/page.tsx
  app/(main)/(light)/study/open/page.tsx
  components/about/IntroduceMemberCard.tsx
  components/common/UnderConstructionDialog.tsx
  components/ui/dialog.tsx
  lib/dummy.ts
  public/under_construction.png
Labels: chore

#70 chore: update dummy data
  .github/ISSUE_TEMPLATE/feature_request.md
  app/(main)/(dark)/page.tsx
  app/(main)/(light)/clubroom/page.tsx
  app/(main)/(light)/study/page.tsx
  components/common/UnderConstructionDialog.tsx
  components/main/StudyCard.tsx
  components/study/StudyCard.tsx
  lib/dummy.ts
  public/clubroom-image/clubroom1.webp
  public/clubroom-image/clubroom2.webp
  public/clubroom-image/clubroom3.webp
  public/clubroom-image/clubroom4.webp
  public/clubroom-image/clubroom5.webp
  public/comit-clubroom.jpg
Labels: chore

#76 hotfix: fix study detail new line, add aws study
  app/(main)/(light)/study/page.tsx
  components/study/StudyCard.tsx
  lib/dummy.ts
Labels: fix, style, chore
