Repository skku-comit/comit-website, pull requests merged in 2024-02, with the labels that each got.

#2 feat: scaffold frontend, add basic layout, add header component
  .eslintignore
  .eslintrc.json
  .gitignore
  .prettierrc
  app/about/page.tsx
  app/components/Header.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  app/room/page.tsx
  app/study/page.tsx
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  public/comit.png
  tailwind.config.ts
  tsconfig.json
Labels: feature

#5 refactor(fe): change folder structure
  app/(main)/_components/Header.tsx
  app/(main)/about/page.tsx
  app/(main)/layout.tsx
  app/(main)/login/page.tsx
  app/(main)/page.tsx
  app/(main)/room/page.tsx
  app/(main)/signup/page.tsx
  app/(main)/study/page.tsx
  app/admin/page.tsx
  app/admin/studies/page.tsx
  app/globals.css
  app/layout.tsx
  package-lock.json
  package.json
Labels: refactor

#9 Feature/7 add header
  app/(main)/_components/Header.tsx
  app/globals.css
  components.json
  components/ui/button.tsx
  lib/utils.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feature

#8 feat(fe): add footer
  app/(main)/_components/Footer.tsx
  app/(main)/_components/Header.tsx
  app/(main)/clubroom/page.tsx
  app/(main)/layout.tsx
  app/(main)/page.tsx
  components/ui/button.tsx
  package-lock.json
  package.json
Labels: feature

#13 docs(fe): create README
  README.md
Labels: docs

#15 feat(fe): add section banner
  app/(main)/about/page.tsx
  app/(main)/clubroom/page.tsx
  app/(main)/layout.tsx
  app/(main)/study/open/page.tsx
  app/(main)/study/page.tsx
  components/common/Footer.tsx
  components/common/Header.tsx
  components/common/SectionBanner.tsx
Labels: feature

#17 feat(fe): add study card
  app/(main)/study/page.tsx
  components/common/Header.tsx
  components/study/StudyCard.tsx
  components/ui/badge.tsx
  components/ui/card.tsx
  package-lock.json
  tailwind.config.ts
Labels: feature

#18 Feature/10 add main page
  app/(main)/page.tsx
  app/(main)/study/page.tsx
  components/main/StudyCard.tsx
  components/ui/carousel.tsx
  package-lock.json
  package.json
  public/mainPicture.svg
Labels: feature

#25 feat(fe): add login page
  app/(main)/clubroom/page.tsx
  app/(main)/login/page.tsx
  app/(main)/signup/page.tsx
  app/(main)/study/page.tsx
  components/common/Footer.tsx
  components/common/Header.tsx
  components/study/StudyCard.tsx
  components/ui/input.tsx
  package-lock.json
  package.json
  public/comitOwl.png
Labels: feature

#22 feat(fe): add study dialog
  app/(main)/page.tsx
  app/(main)/study/page.tsx
  components/main/StudyCard.tsx
  components/study/StudyCard.tsx
  components/ui/dialog.tsx
  lib/dummy.ts
  package-lock.json
  package.json
Labels: feature

#28 feat: make about page
  app/(main)/about/page.tsx
  app/(main)/page.tsx
  components/about/IntroduceMemberCard.tsx
  components/about/SectionCard.tsx
  lib/dummy.ts
  public/about-image/event.svg
  public/about-image/seminar.svg
  public/about-image/studyClass.svg
Labels: feature

#31 make clubroom page
  app/(main)/clubroom/page.tsx
  components/clubroom/ClubroomInfoCard.tsx
  public/comit-clubroom.jpg
Labels: feature

#32 hotfix: change components size
  app/(main)/(dark)/layout.tsx
  app/(main)/(dark)/login/page.tsx
  app/(main)/(dark)/signup/page.tsx
  app/(main)/(light)/about/page.tsx
  app/(main)/(light)/clubroom/page.tsx
  app/(main)/(light)/layout.tsx
  app/(main)/(light)/study/open/page.tsx
  app/(main)/(light)/study/page.tsx
  app/(main)/layout.tsx
  app/(main)/page.tsx
  components/about/IntroduceMemberCard.tsx
  components/clubroom/ClubroomInfoCard.tsx
  components/common/Header.tsx
  components/common/SectionBanner.tsx
  components/study/StudyCard.tsx
  components/ui/drawer.tsx
  package-lock.json
  package.json
Labels: feature, hotfix

#33 hotfix: fix layout bug
  app/(main)/(dark)/layout.tsx
  app/(main)/(dark)/page.tsx
  components/common/Header.tsx
Labels: hotfix

#34 hotfix: fix about auth layout, change drawer responsive to pathname
  app/(main)/(dark)/login/page.tsx
  app/(main)/(dark)/signup/page.tsx
  app/(main)/(light)/about/page.tsx
  components/common/Header.tsx
Labels: hotfix
