Repository skku-comit/comit-website, pull requests merged in 2024-08, with the labels that each got.

#91 fix(fe): default scroll position
  app/(main)/(dark)/layout.tsx
  app/(main)/(light)/layout.tsx
  app/(main)/layout.tsx
  components/common/Header.tsx
Labels: fix, refactor, chore

#90 feat(fe): implement api crud
  app/(main)/(dark)/page.tsx
  app/api/about/route.ts
  app/api/errors/customErrors.ts
  app/api/errors/index.ts
  app/api/errors/standardHttpErrors.ts
  app/api/members/[id]/route.ts
  app/api/members/route.ts
  app/api/studies/[id]/route.ts
  app/api/studies/route.ts
  app/api/study-records/[id]/route.ts
  app/api/study-records/route.ts
  app/api/utils.ts
  app/api/utils/factory.ts
  app/api/utils/httpConsts.ts
  components/about/MemberList.tsx
  components/common/StudyCard/index.tsx
  components/main/ExampleStudyList.tsx
  components/study/StudyList.tsx
  errors/index.ts
  lib/CRUD.ts
  lib/fetch.ts
  types/URL.ts
Labels: fix, API

#95 92 change navbar text color according to url
  app/(main)/(dark)/page.tsx
  app/(main)/(light)/study/open/page.tsx
  components/about/MemberList.tsx
  components/common/Header/NavLink.tsx
  components/common/Header/index.tsx
  components/common/ScrollToTopButton.tsx
  components/study/StudyList.tsx
  constants/apiEndpoint.ts
  constants/routes.ts
  lib/fetch.ts
Labels: chore

#88 Study Open page refactoring
  app/(main)/(light)/study/open/page.tsx
  components/study/StudyList.tsx
  lib/dummy.ts
  types/Study.ts
Labels: feature, refactor

#99 Feat: Open Study Form timepicker & refactoring
  app/(main)/(light)/study/open/page.tsx
  components/ui/badge.tsx
  components/ui/time-picker-input.tsx
  components/ui/time-picker-utils.tsx
  components/ui/timepicker.tsx
  lib/dummy.ts
  package-lock.json
  package.json
  types/Study.ts
Labels: style, feature, refactor

#103 Feat: Framer Motion Wrapper & Main Page Structure
  app/(main)/(dark)/page.tsx
  components/clubroom/ClubroomCarousel.tsx
  components/clubroom/ClubroomMainContent.tsx
  components/common/MotionWrapper.tsx
  components/main/Main.tsx
  components/main/MainCarousel.tsx
  components/ui/button.tsx
  lib/animations.ts
  lib/utils.ts
Labels: feature, refactor

#101 Feat: Study Page ReStyling
  app/(main)/(light)/layout.tsx
  app/(main)/(light)/study/page.tsx
  components/common/ImageSection.tsx
  components/common/SectionBanner.tsx
  components/common/Study/DescriptionCard.tsx
  public/study-image/study.png
Labels: feature

#110 hotfix: set baseURL as localhost
  constants/apiEndpoint.ts
Labels: hotfix, API

#113 fix: seperate studyList fetch from Home page to ExampleStudyList comp…
  app/(main)/(dark)/page.tsx
  components/main/ExampleStudyList.tsx
Labels: refactor

#118 114 add study signup page
  app/(main)/(light)/study/[id]/signup/page.tsx
  app/api/errors/customErrors.ts
  app/api/studies/[id]/route.ts
  app/api/studies/[id]/signup/route.ts
  app/api/utils/httpConsts.ts
  components/common/Header/index.tsx
  components/common/LoadingSpinner.tsx
  components/common/SectionBanner.tsx
  components/study/StudyList.tsx
  components/study/signup/StudySignupForm.tsx
  components/ui/hover-card.tsx
  components/ui/label.tsx
  constants/apiEndpoint.ts
  constants/routes.ts
  database.types.ts
  lib/fetch.ts
  package-lock.json
  package.json
  types/index.ts
Labels: feature

#120 feat: add register-form page first
  app/(main)/(dark)/signup/page.tsx
  app/(main)/(light)/signup/page.tsx
  public/welcome.svg
Labels: feature

#123 Feat: (백엔드X) Auth 초기 로직
  app/(main)/(dark)/login/layout.tsx
  app/(main)/(dark)/login/page.tsx
  app/(main)/(light)/about/page.tsx
  app/(main)/(light)/mystudy/page.tsx
  app/(main)/(light)/profile/page.tsx
  app/(main)/(light)/signup/page.tsx
  app/api/auth/[...nextauth]/route.ts
  components/admin/Header.tsx
  components/common/Header/ClientAuthButton.tsx
  components/common/Header/Dropdown.tsx
  components/common/Header/index.tsx
  components/ui/dropdown-menu.tsx
  constants/apiEndpoint.ts
  constants/routes.ts
  lib/auth/AuthProvider.tsx
  lib/auth/auth.ts
  middleware.ts
  package-lock.json
  package.json
Labels: feature

#130 feat: add auth collection.json
  collections/Admin.postman_collection.json
  collections/Client.postman_collection.json
Labels: test

#126 119 define global communication protocol
  app/(main)/(light)/study/[id]/signup/page.tsx
  app/api/errors/customErrors.ts
  app/api/errors/standardHttpErrors.ts
  app/api/studies/[id]/route.ts
  app/api/studies/[id]/signup/route.ts
  app/api/utils/factory.ts
  app/api/utils/response.ts
  app/api/utils/response/README.md
  app/api/utils/response/index.ts
  app/error.tsx
  components/about/MemberList.tsx
  components/common/Header/NavLink.tsx
  components/main/ExampleStudyList.tsx
  components/study/StudyList.tsx
  components/study/signup/StudySignupForm.tsx
  errors/index.ts
  lib/errors/customErrors.ts
  lib/errors/standardHttpErrors.ts
  lib/errors/types.ts
  lib/fetch.ts
Labels: docs, refactor, API

#128 회원가입 페이지 개선 + clubroom 탭에서 footer 위치 수정
  app/(main)/(light)/clubroom/page.tsx
  app/(main)/(light)/layout.tsx
  app/(main)/(light)/signup/page.tsx
Labels: feature, chore

#132 121 edit study apply page
  app/(main)/(light)/study/[id]/signup/page.tsx
  app/api/studies/[id]/route.ts
  app/api/studies/[id]/signup/route.ts
  app/api/utils/factory.ts
  app/api/utils/response/README.md
  app/api/utils/response/index.ts
  components/about/MemberList.tsx
  components/main/ExampleStudyList.tsx
  components/study/StudyList.tsx
  components/study/signup/StudySignupForm.tsx
  lib/errors/customErrors.ts
  lib/errors/standardHttpErrors.ts
  lib/errors/types.ts
  lib/response/errors.ts
  lib/response/index.ts
Labels: refactor, chore, API

#133 129 edit page layout
  app/(main)/(dark)/layout.tsx
  app/(main)/(dark)/login/page.tsx
  app/(main)/(dark)/page.tsx
  app/(main)/(light)/clubroom/page.tsx
  app/(main)/(light)/layout.tsx
  app/(main)/(light)/study/page.tsx
  app/globals.css
  app/layout.tsx
  components/clubroom/ClubroomMainContent.tsx
  components/common/Footer.tsx
  components/common/Header/index.tsx
  components/common/HeightPopulatedBody.tsx
Labels: fix

#138 chore(fe): add icons and webmanifest file
  app/apple-icon.png
  app/icon.png
  app/manifest.webmanifest
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
Labels: chore

#140 feat(fe): edit login page UI
  app/(main)/(dark)/login/page.tsx
  app/(main)/(light)/signup/page.tsx
Labels: chore

#143 chore(fe): delete dark layout
  app/(main)/about/page.tsx
  app/(main)/clubroom/page.tsx
  app/(main)/login/layout.tsx
  app/(main)/login/page.tsx
  app/(main)/mystudy/page.tsx
  app/(main)/page.tsx
  app/(main)/profile/page.tsx
  app/(main)/signup/page.tsx
  app/(main)/study/[id]/signup/page.tsx
  app/(main)/study/open/page.tsx
  app/(main)/study/page.tsx
  components/about/SectionCard.tsx
  components/common/Footer.tsx
  components/common/Header/Dropdown.tsx
  components/common/Header/NavLink.tsx
  components/common/Header/index.tsx
  components/ui/avatar.tsx
  components/ui/hover-card.tsx
  components/ui/select.tsx
Labels: chore

#155 fix(fe): fix study notice and layout
  app/(main)/study/page.tsx
  components/common/Study/DescriptionCard.tsx
  components/study/StudyList.tsx
Labels: chore

#152 150 add image handling logic
  app/(main)/layout.tsx
  app/(main)/study/open/page.tsx
  app/admin/layout.tsx
  app/api/studies/[id]/route.ts
  app/api/studies/[id]/signup/route.ts
  app/api/studies/route.ts
  app/api/utils/factory.ts
  app/api/utils/index.ts
  app/error.tsx
  app/layout.tsx
  components/common/User/HoverCard.tsx
  components/study/StudyList.tsx
  components/study/signup/StudySignupForm.tsx
  env.d.ts
  lib/supabase/client.ts
  lib/supabase/hooks.ts
  lib/supabase/utils.ts
  next.config.js
  package-lock.json
Labels: feature
