Repository skku-comit/comit-website, pull requests merged in 2024-07, with the labels that each got.

#79 implement api and refactor overall components
  app/(main)/(dark)/page.tsx
  app/(main)/(light)/about/page.tsx
  app/(main)/(light)/clubroom/page.tsx
  app/(main)/(light)/study/open/page.tsx
  app/(main)/(light)/study/page.tsx
  app/admin/closed/page.tsx
  app/admin/opened/page.tsx
  app/admin/reviewing/page.tsx
  app/api/about/route.ts
  app/api/members/[id]/route.ts
  app/api/members/route.ts
  app/api/studies/[id]/route.ts
  app/api/studies/route.ts
  app/api/study-records/[id]/route.ts
  app/api/study-records/route.ts
  app/api/utils.ts
  components/about/IntroduceMemberCard.tsx
  components/about/MemberList.tsx
  components/about/SectionCard.tsx
  components/clubroom/ClubroomCarousel.tsx
  components/clubroom/ClubroomInfoCard.tsx
  components/clubroom/ClubroomMainContent.tsx
  components/columns/Study.tsx
  components/common/DataTable.tsx
  components/common/LoadingSpinner.tsx
  components/common/StudyCard/LazyLoading.tsx
  components/common/StudyCard/index.tsx
  components/main/ExampleStudyList.tsx
  components/main/StudyCard.tsx
  components/study/StudyCard.tsx
  components/study/StudyList.tsx
  errors/index.ts
  lib/dummy.ts
  package-lock.json
  types/Member.ts
  types/Study.ts
  types/index.ts
Labels: refactor, chore, API

#81 refactor: Fix main layout & remove repeated code
  components/common/Footer.tsx
  components/common/Header.tsx
  components/main/ExampleStudyList.tsx
Labels: refactor

#84 Refactor/fetch rsc
  app/(main)/(dark)/page.tsx
  app/(main)/(light)/about/page.tsx
  app/(main)/(light)/study/page.tsx
  app/api/study-records/[id]/route.ts
  app/api/utils.ts
  components/about/MemberList.tsx
  components/about/SectionCard.tsx
  components/clubroom/ClubroomMainContent.tsx
  components/main/ExampleStudyList.tsx
  components/main/Main.tsx
  components/study/StudyList.tsx
  lib/CRUD.ts
  lib/dummy.ts
  types/URL.ts
Labels: fix, refactor

#87 chore: edit prttierrc file
  .prettierrc
  app/(main)/(dark)/layout.tsx
  app/(main)/(dark)/login/page.tsx
  app/(main)/(dark)/signup/page.tsx
  app/(main)/(light)/about/page.tsx
  app/(main)/(light)/clubroom/page.tsx
  app/(main)/(light)/layout.tsx
  app/(main)/(light)/study/open/page.tsx
  app/(main)/(light)/study/page.tsx
  app/(main)/layout.tsx
  app/admin/layout.tsx
  app/api/utils.ts
  components/about/IntroduceMemberCard.tsx
  components/about/SectionCard.tsx
  components/admin/SideBar.tsx
  components/clubroom/ClubroomCarousel.tsx
  components/clubroom/ClubroomInfoCard.tsx
  components/clubroom/ClubroomMainContent.tsx
  components/columns/Study.tsx
  components/common/DataTable.tsx
  components/common/Footer.tsx
  components/common/Header.tsx
  components/common/SectionBanner.tsx
  components/common/StudyCard/LazyLoading.tsx
  components/common/StudyCard/index.tsx
  components/common/UnderConstructionDialog.tsx
  components/ui/alert-dialog.tsx
  components/ui/badge.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/carousel.tsx
  components/ui/dialog.tsx
  components/ui/drawer.tsx
  components/ui/dropdown-menu.tsx
  components/ui/input.tsx
  components/ui/table.tsx
  components/ui/textarea.tsx
  lib/dummy.ts
  tailwind.config.ts
Labels: chore
